services:
  dns:
    image: eduardgabriel/dns-practica:1.1 
    container_name: dns
    hostname: dns
    restart: unless-stopped
    ports:      
      - "53:53"
      - "53:53/udp"  
  apache:
    image: eduardgabriel/apacheldap-eduardmirea:1.0
    container_name: apache
    hostname: apache-service
    ports:
      - "80:80"
      - "443:443"
  openldap:
    image: eduardgabriel/ldap-eduardmirea:1.0
    container_name: openldap
    hostname: openldap-service
    ports:
      - "389:389"
      - "636:636"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "true"
      PHPLDAPADMIN_HTTPS_PORT: 443
    depends_on:
      - openldap