version: '3.9'

services:
  dns:
    build: ./dns
    container_name: dns
    image: minombreapellido/dns
    ports:
      - "1053:53/udp"
  
  ldap:
    build: ./ldap
    container_name: ldap
    image: minombreapellido/ldap
    ports:
      - "389:389"
    
    environment:
      LDAP_ORGANISATION: "minombreapellido.local"
      LDAP_DOMAIN: "minombreapellido.local"
      LDAP_ADMIN_PASSWORD: "ieselcaminas"
  
  phpldapadmin:
    build: ./phpldapadmin
    container_name: phpldapadmin
    image: minombreapellido/phpldapadmin
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS:  ldap
