FROM internetsystemsconsortium/bind9:9.18

COPY named.conf /etc/bind/named.conf
COPY named.conf.local /etc/bind/named.conf.local
COPY named.conf.options /etc/bind/named.conf.options
COPY db.eduardmirea.local /etc/bind/db.eduardmirea.local